import test from 'node:test';import assert from 'node:assert/strict';
import {aggregate,cnpj,number,month,compileImport,autoMapping,filterBase,byProfile} from '../public/engine.mjs';
import {demoBase,sampleSheets} from '../public/demo.mjs';import * as XLSX from '../public/vendor/xlsx.mjs';import fs from 'node:fs';
const A='12345678000195',B='11222333000181';
function sheet(name,role,headers,rows){return {name,role,headers,rows,map:autoMapping(headers,role)};}
export function fixture(){return [sheet('Cadastro','clients',['CNPJ','Cliente','Perfil','UF'],[[A,'Cliente A','Rede A','ES'],[B,'Cliente B','Rede B','RJ']]),sheet('Janeiro','sales',['Data','CNPJ','Tipo','Grupo','Formato','Quantidade','Valor bruto','Devolução','Peso líquido'],[['2026-01-01',A,'Venda','Pizza','F15',900,3000,0,90],['2026-01-02',A,'Devolução','Pizza','F15',90,300,0,9],['2026-01-01',B,'Venda','Pizza','F30',600,6000,0,180],['2026-01-01',B,'Venda','Pastel','',100,1000,0,50],['2026-01-01',A,'Bonificação','Pizza','F30',100,1000,0,30]]),sheet('Fevereiro','sales',['Data','CNPJ','Tipo','Grupo','Formato','Quantidade','Valor bruto','Devolução','Peso líquido'],[['2026-02-01',A,'Venda','Pizza','F25',600,6000,0,180]]),sheet('Metas','goals',['Mês','CNPJ','Grupo','Meta venda','Meta UP','Meta peso'],[['2026-01',A,'Pizza',3000,300,90],['2026-02',A,'Pizza',6000,600,180],['2026-01',B,'Pizza',6000,600,180],['2026-01',B,'Pastel',1000,'',50]]),sheet('Pessoas','people',['Mês','CNPJ','Pessoas efetivas'],[['2026-01',A,2],['2026-02',A,4],['2026-01',B,3]])];}
const compiled=()=>{const r=compileImport(fixture(),'Fixture');assert.deepEqual(r.errors,[]);return r.base;};
test('known totals: returns, F15 conversion, pastel and bonus exclusion',()=>{const b=compiled(),a=aggregate(b,{});assert.equal(a.gross,16000);assert.equal(a.returns,300);assert.equal(a.revenue,15700);assert.equal(a.up,1470);assert.equal(a.weight,491);assert.equal(a.people,9);assert.equal(a.target,16000);assert.equal(a.attainment,98.125);assert.equal(a.productivity,1470/9);assert.equal(a.gap,-300);assert.equal(a.rows,5);});
test('multiple months: ratio of sums, not average ratios',()=>{const a=aggregate(compiled(),{profile:'Rede A',start:'2026-01',end:'2026-02'});assert.equal(a.productivity,145);assert.equal(a.up,870);assert.equal(a.people,6);assert.equal(a.revenue,8700);assert.notEqual(a.productivity,(135+150)/2);});
test('all filters affect numerator, denominator and targets',()=>{const b=compiled();const a=aggregate(b,{start:'2026-01',end:'2026-01',profile:'Rede A',uf:'ES',group:'Pizza'});assert.equal(a.revenue,2700);assert.equal(a.target,3000);assert.equal(a.attainment,90);assert.equal(a.up,270);assert.equal(a.weight,81);assert.equal(a.productivity,135);assert.equal(a.people,2);const empty=aggregate(b,{profile:'Rede A',uf:'RJ'});assert.equal(empty.revenue,0);assert.equal(empty.productivity,null);assert.equal(empty.target,null);});
test('pastel excluded from UP and productivity',()=>{const a=aggregate(compiled(),{group:'Pastel'});assert.equal(a.up,0);assert.equal(a.weight,50);assert.equal(a.revenue,1000);assert.equal(a.productivity,null);assert.equal(a.people,0);assert.equal(a.attainment,100);});
test('profile totals reconcile with general total',()=>{const b=compiled(),r=byProfile(b,{}),a=aggregate(b,{});for(const k of ['revenue','target','up','weight','people'])assert.equal(r.reduce((v,x)=>v+x[k],0),a[k]);});
test('CNPJ normalization and checksum; missing/unknown CNPJ blocks',()=>{assert.equal(cnpj('12.345.678/0001-95'),A);assert.throws(()=>cnpj('12345678000194'));assert.throws(()=>cnpj(''));const s=fixture();s[1].rows[0][1]='04252011000110';assert.match(compileImport(s).errors.join(' '),/sem correspondência/);});
test('duplicate customer, target or workforce keys block',()=>{for(const i of [0,3,4]){const s=fixture();s[i].rows.push([...s[i].rows[0]]);assert.ok(compileImport(s).errors.some(e=>/duplicad/.test(e)));}});
test('missing people suppresses aggregate productivity',()=>{const b=compiled();b.people=b.people.filter(x=>x.month!=='2026-02');const a=aggregate(b,{});assert.equal(a.productivity,null);assert.equal(a.missingPeople,1);});
test('missing, partial and zero targets do not produce misleading attainment',()=>{const b=compiled();b.goals=b.goals.slice(1);assert.equal(aggregate(b,{}).attainment,null);b.goals=[];assert.equal(aggregate(b,{}).target,null);assert.equal(aggregate(b,{}).attainment,null);b.goals=compiled().goals.map(r=>({...r,revenue:0}));assert.equal(aggregate(b,{}).attainment,null);});
test('explicit zero and missing data distinguished; invalid numeric data blocked',()=>{assert.equal(number(0),0);assert.equal(number('',true),null);assert.throws(()=>number(''));assert.equal(number('R$ 1.234,56'),1234.56);assert.throws(()=>number('12abc'));const s=fixture();s[1].rows[0][8]='';assert.ok(compileImport(s).errors.length);});
test('date formats',()=>{assert.equal(month('01/2026'),'2026-01');assert.equal(month('31/01/2026'),'2026-01');assert.equal(month('2026-01-01'),'2026-01');assert.equal(month(46023),'2026-01');assert.throws(()=>month('31/02/2026'));assert.throws(()=>month('2026-13'));});
test('explicit UP takes precedence; pastel UP remains excluded',()=>{const s=fixture();s[1].headers.push('UP');s[1].rows[0].push(500);s[1].rows[3].push(800);s[1].map=autoMapping(s[1].headers,'sales');const b=compileImport(s);assert.deepEqual(b.errors,[]);assert.equal(aggregate(b.base,{}).up,1670);});
test('F25 F30 F35 equal 1 UP/unit, F15 divides by 3',()=>{for(const format of ['F25','F30','F35','F15']){const s=fixture();s[1].rows[0][4]=format;const b=compileImport(s).base;assert.equal(b.sales[0].up,format==='F15'?300:900);}});
test('return values cannot be double counted in return rows',()=>{const s=fixture();s[1].rows[1][7]=300;assert.ok(compileImport(s).errors.some(e=>/deixe Devolução/.test(e)));});
test('XLSX and binary XLS files: multiple sheets roundtrip',()=>{fs.mkdirSync('tests/fixtures',{recursive:true});for(const bookType of ['xlsx','xls']){const wb=XLSX.utils.book_new();for(const s of fixture())XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([s.headers,...s.rows]),s.name);const bytes=XLSX.write(wb,{type:'buffer',bookType:bookType==='xls'?'biff8':'xlsx'});fs.writeFileSync(`tests/fixtures/valid.${bookType}`,bytes);const rb=XLSX.read(bytes,{type:'buffer',cellDates:true});const ss=rb.SheetNames.map((name,i)=>{const rows=XLSX.utils.sheet_to_json(rb.Sheets[name],{header:1,defval:'',raw:true});return sheet(name,fixture()[i].role,rows[0],rows.slice(1));});const r=compileImport(ss);assert.deepEqual(r.errors,[]);assert.equal(aggregate(r.base,{}).revenue,15700);assert.equal(aggregate(r.base,{}).up,1470);}});
test('demo has exact reproducible totals',()=>{const a=aggregate(demoBase(),{});assert.equal(a.revenue,896646);assert.equal(a.up,250464);assert.equal(a.weight,74504);assert.equal(a.productivity,2609);assert.equal(a.target,926785);assert.equal(a.rows,192);});
